version: "3.9"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sampleDB
    ports:
      - "3306:3306"
    networks:
      - mysql-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-db
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
    networks:
      - mysql-network
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    networks:
      - mysql-network
    hostname: zookeeper

  broker01:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: broker01
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    networks:
      - mysql-network

networks:
  mysql-network: